--
-- Create table for `employees`
--
CREATE TABLE `employees` (
  `id` bigint(20) generated by default as identity NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `yearly_income` bigint(20) NOT NULL
);